package zone

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/miekg/dns"
	"github.com/prenansantana/extract-zone-file/resolver"
)

// Record type display order.
var typeOrder = []uint16{
	dns.TypeSOA,
	dns.TypeNS,
	dns.TypeA,
	dns.TypeAAAA,
	dns.TypeCNAME,
	dns.TypeMX,
	dns.TypeTXT,
	dns.TypeSRV,
	dns.TypeCAA,
	dns.TypePTR,
}

var typeNames = map[uint16]string{
	dns.TypeSOA:   "SOA Records",
	dns.TypeNS:    "NS Records",
	dns.TypeA:     "A Records",
	dns.TypeAAAA:  "AAAA Records",
	dns.TypeCNAME: "CNAME Records",
	dns.TypeMX:    "MX Records",
	dns.TypeTXT:   "TXT Records",
	dns.TypeSRV:   "SRV Records",
	dns.TypeCAA:   "CAA Records",
	dns.TypePTR:   "PTR Records",
}

// Format produces a BIND zone file string from a RecordSet.
func Format(rs *resolver.RecordSet) string {
	var b strings.Builder

	// Header.
	fmt.Fprintf(&b, "; Zone file for %s\n", strings.TrimSuffix(rs.Domain, "."))
	fmt.Fprintf(&b, "; Generated by zoneextract on %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "; Queried server: %s\n", rs.Server)
	if rs.AXFRSuccess {
		fmt.Fprintln(&b, "; Source: zone transfer (AXFR)")
	} else {
		fmt.Fprintln(&b, "; NOTE: Best-effort reconstruction via individual queries.")
	}
	fmt.Fprintln(&b)

	// $ORIGIN directive.
	fmt.Fprintf(&b, "$ORIGIN %s\n", rs.Domain)

	// Extract TTL from SOA if available.
	ttl := uint32(300)
	for _, rr := range rs.Records {
		if soa, ok := rr.(*dns.SOA); ok {
			ttl = soa.Minttl
			break
		}
	}
	fmt.Fprintf(&b, "$TTL %d\n", ttl)

	// Group records by type.
	grouped := make(map[uint16][]dns.RR)
	for _, rr := range rs.Records {
		t := rr.Header().Rrtype
		grouped[t] = append(grouped[t], rr)
	}

	// Output in defined order.
	for _, t := range typeOrder {
		records, ok := grouped[t]
		if !ok || len(records) == 0 {
			continue
		}

		sort.Slice(records, func(i, j int) bool {
			return records[i].String() < records[j].String()
		})

		name := typeNames[t]
		if name == "" {
			name = fmt.Sprintf("Type %d Records", t)
		}

		fmt.Fprintf(&b, "\n; %s\n", name)
		for _, rr := range records {
			fmt.Fprintln(&b, rr.String())
		}
	}

	// Any remaining types not in typeOrder.
	for t, records := range grouped {
		found := false
		for _, ot := range typeOrder {
			if t == ot {
				found = true
				break
			}
		}
		if found {
			continue
		}

		sort.Slice(records, func(i, j int) bool {
			return records[i].String() < records[j].String()
		})

		fmt.Fprintf(&b, "\n; Type %d Records\n", t)
		for _, rr := range records {
			fmt.Fprintln(&b, rr.String())
		}
	}

	return b.String()
}
